apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.votingApp.gitRepoURL }}
    targetRevision: main
    path: terraform/eks-deployment/gitops/cluster-configs
    helm:
      valuesObject:
        duckdns:
          clusterIssuer:
            name: {{ .Values.duckdns.clusterIssuer.name }}
            email: {{ .Values.duckdns.clusterIssuer.email }}
            groupName: {{ .Values.duckdns.clusterIssuer.groupName }}
          tokenSecretName: {{ .Values.duckdns.tokenSecretName }}
        externalSecrets:
          serviceAccount:
            name: {{ .Values.externalSecrets.serviceAccount.name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true