apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io/
    chart: external-secrets
    targetRevision: "2.2.0"
    helm:
      valuesObject:
        serviceAccount:
          name: {{ .Values.externalSecrets.serviceAccount.name }}
          annotations:
            eks.amazonaws.com/role-arn: {{ .Values.externalSecrets.irsaRoleArn }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true