apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: duckdns-token-sync
  namespace: cert-manager
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.duckdns.tokenSecretName }}
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.duckdns.tokenSecretName }}