# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "voting-app-terraform-backend"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "environments/dev/network/terraform.tfstate"
    region         = "us-east-1"
  }
}
