global:
  security:
    allowInsecureImages: true

fullnameOverride: ""

result:
  replicaCount: 1

  image:
    registry: "docker.io"
    repository: "kuriy/voting-app-result"
    tag: "latest"

  service:
    type: "ClusterIP"
    externalPort: 8081
    internalPort: 80
    nodePort: 30081
    name: "result"

vote:
  replicaCount: 1

  image:
    registry: "docker.io"
    repository: "kuriy/voting-app-vote"
    tag: "latest"

  service:
    type: "ClusterIP"
    externalPort: 8080
    internalPort: 80
    nodePort: 30080
    name: "vote"

worker:
  replicaCount: 1

  image:
    registry: "docker.io"
    repository: "kuriy/voting-app-worker"
    tag: "latest"

redis:
  networkPolicy:
    enabled: false
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  image:
    registry: "public.ecr.aws"
    repository: "bitnami/redis"
    tag: "latest"

postgresql:
  networkPolicy:
    enabled: false
  auth:
    enabled: true
    database: "votingdb"
    username: "votingUser"
    password: "Password123_"
    existingSecret: ""
    secretKeys:
      userPassword: "password"
  primary:
    persistence:
      enabled: false
  image:
    registry: "public.ecr.aws"
    repository: "bitnami/postgresql"
    tag: "latest"

gateway:
  enabled: false
  gatewayClassName: ""
  listeners:
    - name:
      protocol:
      port: 
  routing:
    vote:
      hostname: ""
      path: /
    result:
      hostname: ""
      path: /

ingress:
  enabled: true
  scheme: internet-facing
  hosts:
    vote: "asd"
    result: "asd"